# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBar.setBaseSize(QtCore.QSize(2, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft Himalaya")
        font.setPointSize(22)
        self.toolBar.setFont(font)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(70, 70))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actSetWeight1 = QtWidgets.QAction(MainWindow)
        self.actSetWeight1.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/weigh-Medium.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actSetWeight1.setIcon(icon)
        font = QtGui.QFont()
        font.setFamily("Microsoft Himalaya")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.actSetWeight1.setFont(font)
        self.actSetWeight1.setObjectName("actSetWeight1")
        self.actWelcome = QtWidgets.QAction(MainWindow)
        self.actWelcome.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/icons/car-Medium.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actWelcome.setIcon(icon1)
        font = QtGui.QFont()
        font.setFamily("Microsoft Himalaya")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.actWelcome.setFont(font)
        self.actWelcome.setObjectName("actWelcome")
        self.actImport = QtWidgets.QAction(MainWindow)
        self.actImport.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/icons/files.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actImport.setIcon(icon2)
        font = QtGui.QFont()
        font.setFamily("Microsoft Himalaya")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.actImport.setFont(font)
        self.actImport.setObjectName("actImport")
        self.actCompare1 = QtWidgets.QAction(MainWindow)
        self.actCompare1.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/icons/data, graph-Medium.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actCompare1.setIcon(icon3)
        font = QtGui.QFont()
        font.setFamily("Microsoft Himalaya")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.actCompare1.setFont(font)
        self.actCompare1.setObjectName("actCompare1")
        self.actResult1 = QtWidgets.QAction(MainWindow)
        self.actResult1.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/icons/data, graph, trend-Medium.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actResult1.setIcon(icon4)
        font = QtGui.QFont()
        font.setFamily("Microsoft Himalaya")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.actResult1.setFont(font)
        self.actResult1.setObjectName("actResult1")
        self.actMode = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/icons/change.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actMode.setIcon(icon5)
        font = QtGui.QFont()
        font.setFamily("Microsoft Himalaya")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.actMode.setFont(font)
        self.actMode.setObjectName("actMode")
        self.actSetTarget = QtWidgets.QAction(MainWindow)
        self.actSetTarget.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/icons/task-Medium-blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actSetTarget.setIcon(icon6)
        font = QtGui.QFont()
        font.setFamily("Microsoft Himalaya")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.actSetTarget.setFont(font)
        self.actSetTarget.setObjectName("actSetTarget")
        self.actSetWeight2 = QtWidgets.QAction(MainWindow)
        self.actSetWeight2.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/images/icons/weigh-Medium-blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actSetWeight2.setIcon(icon7)
        font = QtGui.QFont()
        font.setFamily("Microsoft Himalaya")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.actSetWeight2.setFont(font)
        self.actSetWeight2.setObjectName("actSetWeight2")
        self.actCompare2 = QtWidgets.QAction(MainWindow)
        self.actCompare2.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/images/icons/data, graph-Medium-blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actCompare2.setIcon(icon8)
        font = QtGui.QFont()
        font.setFamily("Microsoft Himalaya")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.actCompare2.setFont(font)
        self.actCompare2.setObjectName("actCompare2")
        self.actResult2 = QtWidgets.QAction(MainWindow)
        self.actResult2.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/images/icons/data, graph, trend-Medium-blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actResult2.setIcon(icon9)
        font = QtGui.QFont()
        font.setFamily("Microsoft Himalaya")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.actResult2.setFont(font)
        self.actResult2.setObjectName("actResult2")
        self.toolBar.addAction(self.actWelcome)
        self.toolBar.addAction(self.actImport)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actMode)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actSetWeight1)
        self.toolBar.addAction(self.actCompare1)
        self.toolBar.addAction(self.actResult1)
        self.toolBar.addAction(self.actSetTarget)
        self.toolBar.addAction(self.actSetWeight2)
        self.toolBar.addAction(self.actCompare2)
        self.toolBar.addAction(self.actResult2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actSetWeight1.setText(_translate("MainWindow", "    Weight    "))
        self.actSetWeight1.setToolTip(_translate("MainWindow", "Set weight for each parameter to compare similarities between vehicles."))
        self.actWelcome.setText(_translate("MainWindow", "Welcome"))
        self.actImport.setText(_translate("MainWindow", "    Import    "))
        self.actImport.setToolTip(_translate("MainWindow", "Import vehicles"))
        self.actCompare1.setText(_translate("MainWindow", "Compare"))
        self.actCompare1.setToolTip(_translate("MainWindow", "Compare similarities between vehicles"))
        self.actResult1.setText(_translate("MainWindow", "    Result    "))
        self.actResult1.setToolTip(_translate("MainWindow", "Display result"))
        self.actMode.setText(_translate("MainWindow", "Reliability"))
        self.actMode.setToolTip(_translate("MainWindow", "Change the evaluation mode"))
        self.actSetTarget.setText(_translate("MainWindow", "Target"))
        self.actSetTarget.setToolTip(_translate("MainWindow", "Set target value for each parameter."))
        self.actSetWeight2.setText(_translate("MainWindow", "Weight"))
        self.actSetWeight2.setToolTip(_translate("MainWindow", "Set weight for each parameter to find how close the vehicle data is to the target data."))
        self.actCompare2.setText(_translate("MainWindow", "Compare"))
        self.actCompare2.setToolTip(_translate("MainWindow", "Find how close the vehicle data is to the target data."))
        self.actResult2.setText(_translate("MainWindow", "Result"))
        self.actResult2.setToolTip(_translate("MainWindow", "Display result"))

import res_rc
