# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QWFormSetWeight1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QWFormSetWeight1(object):
    def setupUi(self, QWFormSetWeight1):
        QWFormSetWeight1.setObjectName("QWFormSetWeight1")
        QWFormSetWeight1.resize(400, 300)
        self.tabWidget = QtWidgets.QTabWidget(QWFormSetWeight1)
        self.tabWidget.setGeometry(QtCore.QRect(9, 35, 278, 238))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.overall = QtWidgets.QWidget()
        self.overall.setObjectName("overall")
        self.gridLayout = QtWidgets.QGridLayout(self.overall)
        self.gridLayout.setObjectName("gridLayout")
        self.tree_overall = QtWidgets.QTreeWidget(self.overall)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.tree_overall.setFont(font)
        self.tree_overall.setObjectName("tree_overall")
        self.gridLayout.addWidget(self.tree_overall, 0, 0, 1, 1)
        self.tabWidget.addTab(self.overall, "")
        self.test1 = QtWidgets.QWidget()
        self.test1.setObjectName("test1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.test1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tree_test1 = QtWidgets.QTreeWidget(self.test1)
        self.tree_test1.setObjectName("tree_test1")
        self.gridLayout_2.addWidget(self.tree_test1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.test1, "")
        self.test2 = QtWidgets.QWidget()
        self.test2.setObjectName("test2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.test2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tree_test2 = QtWidgets.QTreeWidget(self.test2)
        self.tree_test2.setObjectName("tree_test2")
        self.gridLayout_3.addWidget(self.tree_test2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.test2, "")
        self.test3 = QtWidgets.QWidget()
        self.test3.setObjectName("test3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.test3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tree_test3 = QtWidgets.QTreeWidget(self.test3)
        self.tree_test3.setObjectName("tree_test3")
        self.gridLayout_4.addWidget(self.tree_test3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.test3, "")
        self.test4 = QtWidgets.QWidget()
        self.test4.setObjectName("test4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.test4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tree_test4 = QtWidgets.QTreeWidget(self.test4)
        self.tree_test4.setObjectName("tree_test4")
        self.gridLayout_5.addWidget(self.tree_test4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.test4, "")
        self.test5 = QtWidgets.QWidget()
        self.test5.setObjectName("test5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.test5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tree_test5 = QtWidgets.QTreeWidget(self.test5)
        self.tree_test5.setObjectName("tree_test5")
        self.gridLayout_6.addWidget(self.tree_test5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.test5, "")
        self.test6 = QtWidgets.QWidget()
        self.test6.setObjectName("test6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.test6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tree_test6 = QtWidgets.QTreeWidget(self.test6)
        self.tree_test6.setObjectName("tree_test6")
        self.gridLayout_7.addWidget(self.tree_test6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.test6, "")
        self.test7 = QtWidgets.QWidget()
        self.test7.setObjectName("test7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.test7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tree_test7 = QtWidgets.QTreeWidget(self.test7)
        self.tree_test7.setObjectName("tree_test7")
        self.gridLayout_8.addWidget(self.tree_test7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.test7, "")
        self.test8 = QtWidgets.QWidget()
        self.test8.setObjectName("test8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.test8)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tree_test8 = QtWidgets.QTreeWidget(self.test8)
        self.tree_test8.setObjectName("tree_test8")
        self.gridLayout_9.addWidget(self.tree_test8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.test8, "")
        self.test10 = QtWidgets.QWidget()
        self.test10.setObjectName("test10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.test10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tree_test10 = QtWidgets.QTreeWidget(self.test10)
        self.tree_test10.setObjectName("tree_test10")
        self.gridLayout_10.addWidget(self.tree_test10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.test10, "")
        self.strapped = QtWidgets.QWidget()
        self.strapped.setObjectName("strapped")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.strapped)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.tree_strapped = QtWidgets.QTreeWidget(self.strapped)
        self.tree_strapped.setObjectName("tree_strapped")
        self.gridLayout_11.addWidget(self.tree_strapped, 0, 0, 1, 1)
        self.tabWidget.addTab(self.strapped, "")
        self.actImport = QtWidgets.QAction(QWFormSetWeight1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.actImport.setFont(font)
        self.actImport.setObjectName("actImport")
        self.actSave = QtWidgets.QAction(QWFormSetWeight1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.actSave.setFont(font)
        self.actSave.setObjectName("actSave")
        self.actResetAll = QtWidgets.QAction(QWFormSetWeight1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.actResetAll.setFont(font)
        self.actResetAll.setObjectName("actResetAll")
        self.actUndo = QtWidgets.QAction(QWFormSetWeight1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.actUndo.setFont(font)
        self.actUndo.setObjectName("actUndo")
        self.actRedo = QtWidgets.QAction(QWFormSetWeight1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.actRedo.setFont(font)
        self.actRedo.setObjectName("actRedo")
        self.actResetLoc = QtWidgets.QAction(QWFormSetWeight1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.actResetLoc.setFont(font)
        self.actResetLoc.setObjectName("actResetLoc")
        self.actSeparator1 = QtWidgets.QAction(QWFormSetWeight1)
        self.actSeparator1.setEnabled(False)
        self.actSeparator1.setObjectName("actSeparator1")
        self.actSeparator2 = QtWidgets.QAction(QWFormSetWeight1)
        self.actSeparator2.setEnabled(False)
        self.actSeparator2.setObjectName("actSeparator2")
        self.actSeparator3 = QtWidgets.QAction(QWFormSetWeight1)
        self.actSeparator3.setEnabled(False)
        self.actSeparator3.setObjectName("actSeparator3")

        self.retranslateUi(QWFormSetWeight1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QWFormSetWeight1)

    def retranslateUi(self, QWFormSetWeight1):
        _translate = QtCore.QCoreApplication.translate
        QWFormSetWeight1.setWindowTitle(_translate("QWFormSetWeight1", "Form"))
        self.tabWidget.setWhatsThis(_translate("QWFormSetWeight1", "<html><head/><body><p><br/></p></body></html>"))
        self.tree_overall.headerItem().setText(0, _translate("QWFormSetWeight1", "Tests"))
        self.tree_overall.headerItem().setText(1, _translate("QWFormSetWeight1", "Weight (%)"))
        self.tree_overall.headerItem().setText(2, _translate("QWFormSetWeight1", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.overall), _translate("QWFormSetWeight1", "Overall"))
        self.tree_test1.headerItem().setText(0, _translate("QWFormSetWeight1", "Parameters"))
        self.tree_test1.headerItem().setText(1, _translate("QWFormSetWeight1", "Weight (%)"))
        self.tree_test1.headerItem().setText(2, _translate("QWFormSetWeight1", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test1), _translate("QWFormSetWeight1", "Long. braking"))
        self.tree_test2.headerItem().setText(0, _translate("QWFormSetWeight1", "Parameters"))
        self.tree_test2.headerItem().setText(1, _translate("QWFormSetWeight1", "Weight (%)"))
        self.tree_test2.headerItem().setText(2, _translate("QWFormSetWeight1", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test2), _translate("QWFormSetWeight1", "Lat. 0_in"))
        self.tree_test3.headerItem().setText(0, _translate("QWFormSetWeight1", "Parameters"))
        self.tree_test3.headerItem().setText(1, _translate("QWFormSetWeight1", "Weight (%)"))
        self.tree_test3.headerItem().setText(2, _translate("QWFormSetWeight1", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test3), _translate("QWFormSetWeight1", "Lat. 0_anti"))
        self.tree_test4.headerItem().setText(0, _translate("QWFormSetWeight1", "Parameters"))
        self.tree_test4.headerItem().setText(1, _translate("QWFormSetWeight1", "Weight (%)"))
        self.tree_test4.headerItem().setText(2, _translate("QWFormSetWeight1", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test4), _translate("QWFormSetWeight1", "Lat. -30_in"))
        self.tree_test5.headerItem().setText(0, _translate("QWFormSetWeight1", "Parameters"))
        self.tree_test5.headerItem().setText(1, _translate("QWFormSetWeight1", "Weight (%)"))
        self.tree_test5.headerItem().setText(2, _translate("QWFormSetWeight1", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test5), _translate("QWFormSetWeight1", "Alig. T_in"))
        self.tree_test6.headerItem().setText(0, _translate("QWFormSetWeight1", "Parameters"))
        self.tree_test6.headerItem().setText(1, _translate("QWFormSetWeight1", "Weight (%)"))
        self.tree_test6.headerItem().setText(2, _translate("QWFormSetWeight1", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test6), _translate("QWFormSetWeight1", "Alig. T_anti"))
        self.tree_test7.headerItem().setText(0, _translate("QWFormSetWeight1", "Parameters"))
        self.tree_test7.headerItem().setText(1, _translate("QWFormSetWeight1", "Weight (%)"))
        self.tree_test7.headerItem().setText(2, _translate("QWFormSetWeight1", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test7), _translate("QWFormSetWeight1", "Steering"))
        self.tree_test8.headerItem().setText(0, _translate("QWFormSetWeight1", "Parameters"))
        self.tree_test8.headerItem().setText(1, _translate("QWFormSetWeight1", "Weight (%)"))
        self.tree_test8.headerItem().setText(2, _translate("QWFormSetWeight1", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test8), _translate("QWFormSetWeight1", "Roll"))
        self.tree_test10.headerItem().setText(0, _translate("QWFormSetWeight1", "Parameters"))
        self.tree_test10.headerItem().setText(1, _translate("QWFormSetWeight1", "Weight (%)"))
        self.tree_test10.headerItem().setText(2, _translate("QWFormSetWeight1", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test10), _translate("QWFormSetWeight1", "Vertical"))
        self.tree_strapped.headerItem().setText(0, _translate("QWFormSetWeight1", "Parameters"))
        self.tree_strapped.headerItem().setText(1, _translate("QWFormSetWeight1", "Weight (%)"))
        self.tree_strapped.headerItem().setText(2, _translate("QWFormSetWeight1", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.strapped), _translate("QWFormSetWeight1", "Long. acc"))
        self.actImport.setText(_translate("QWFormSetWeight1", "Import Setting"))
        self.actSave.setText(_translate("QWFormSetWeight1", "Save Setting As"))
        self.actResetAll.setText(_translate("QWFormSetWeight1", "Reset All"))
        self.actUndo.setText(_translate("QWFormSetWeight1", "Undo"))
        self.actRedo.setText(_translate("QWFormSetWeight1", "Redo"))
        self.actResetLoc.setText(_translate("QWFormSetWeight1", "Reset Current Page"))
        self.actSeparator1.setText(_translate("QWFormSetWeight1", "|"))
        self.actSeparator2.setText(_translate("QWFormSetWeight1", "|"))
        self.actSeparator3.setText(_translate("QWFormSetWeight1", "|"))

