# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QWFormSetWeight2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QWFormSetWeight2(object):
    def setupUi(self, QWFormSetWeight2):
        QWFormSetWeight2.setObjectName("QWFormSetWeight2")
        QWFormSetWeight2.resize(474, 342)
        self.tabWidget = QtWidgets.QTabWidget(QWFormSetWeight2)
        self.tabWidget.setGeometry(QtCore.QRect(20, 40, 278, 244))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.overall = QtWidgets.QWidget()
        self.overall.setObjectName("overall")
        self.gridLayout = QtWidgets.QGridLayout(self.overall)
        self.gridLayout.setObjectName("gridLayout")
        self.tree_overall = QtWidgets.QTreeWidget(self.overall)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.tree_overall.setFont(font)
        self.tree_overall.setObjectName("tree_overall")
        self.gridLayout.addWidget(self.tree_overall, 0, 0, 1, 1)
        self.tabWidget.addTab(self.overall, "")
        self.general = QtWidgets.QWidget()
        self.general.setEnabled(True)
        self.general.setObjectName("general")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.general)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tree_general = QtWidgets.QTreeWidget(self.general)
        self.tree_general.setObjectName("tree_general")
        self.gridLayout_7.addWidget(self.tree_general, 0, 0, 1, 1)
        self.tabWidget.addTab(self.general, "")
        self.longi = QtWidgets.QWidget()
        self.longi.setObjectName("longi")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.longi)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tree_longi = QtWidgets.QTreeWidget(self.longi)
        self.tree_longi.setObjectName("tree_longi")
        self.gridLayout_2.addWidget(self.tree_longi, 0, 0, 1, 1)
        self.tabWidget.addTab(self.longi, "")
        self.lateral = QtWidgets.QWidget()
        self.lateral.setObjectName("lateral")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.lateral)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tree_lateral = QtWidgets.QTreeWidget(self.lateral)
        self.tree_lateral.setObjectName("tree_lateral")
        self.gridLayout_3.addWidget(self.tree_lateral, 0, 0, 1, 1)
        self.tabWidget.addTab(self.lateral, "")
        self.vertical = QtWidgets.QWidget()
        self.vertical.setObjectName("vertical")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.vertical)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tree_vertical = QtWidgets.QTreeWidget(self.vertical)
        self.tree_vertical.setObjectName("tree_vertical")
        self.gridLayout_4.addWidget(self.tree_vertical, 0, 0, 1, 1)
        self.tabWidget.addTab(self.vertical, "")
        self.steer = QtWidgets.QWidget()
        self.steer.setObjectName("steer")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.steer)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tree_steer = QtWidgets.QTreeWidget(self.steer)
        self.tree_steer.setObjectName("tree_steer")
        self.gridLayout_5.addWidget(self.tree_steer, 0, 0, 1, 1)
        self.tabWidget.addTab(self.steer, "")
        self.roll = QtWidgets.QWidget()
        self.roll.setObjectName("roll")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.roll)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tree_roll = QtWidgets.QTreeWidget(self.roll)
        self.tree_roll.setObjectName("tree_roll")
        self.gridLayout_6.addWidget(self.tree_roll, 1, 0, 1, 1)
        self.tabWidget.addTab(self.roll, "")
        self.label = QtWidgets.QLabel(QWFormSetWeight2)
        self.label.setGeometry(QtCore.QRect(9, 9, 185, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(QWFormSetWeight2)
        self.label_2.setGeometry(QtCore.QRect(244, 9, 176, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setObjectName("label_2")
        self.weightF = QtWidgets.QLineEdit(QWFormSetWeight2)
        self.weightF.setGeometry(QtCore.QRect(200, 9, 70, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weightF.sizePolicy().hasHeightForWidth())
        self.weightF.setSizePolicy(sizePolicy)
        self.weightF.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.weightF.setFont(font)
        self.weightF.setStyleSheet("QLineEdit{\n"
"    border: 2px groove gray;\n"
"    border-radius: 14px;\n"
"    padding: 2px 4px;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(255, 140 ,0);\n"
"}")
        self.weightF.setAlignment(QtCore.Qt.AlignCenter)
        self.weightF.setObjectName("weightF")
        self.weightR = QtWidgets.QLineEdit(QWFormSetWeight2)
        self.weightR.setGeometry(QtCore.QRect(426, 9, 20, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weightR.sizePolicy().hasHeightForWidth())
        self.weightR.setSizePolicy(sizePolicy)
        self.weightR.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.weightR.setFont(font)
        self.weightR.setStyleSheet("QLineEdit{\n"
"    border: 2px groove gray;\n"
"    border-radius: 14px;\n"
"    padding: 2px 4px;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(255, 140 ,0);\n"
"}")
        self.weightR.setAlignment(QtCore.Qt.AlignCenter)
        self.weightR.setObjectName("weightR")
        self.actImport = QtWidgets.QAction(QWFormSetWeight2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.actImport.setFont(font)
        self.actImport.setObjectName("actImport")
        self.actSave = QtWidgets.QAction(QWFormSetWeight2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.actSave.setFont(font)
        self.actSave.setObjectName("actSave")
        self.actResetAll = QtWidgets.QAction(QWFormSetWeight2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.actResetAll.setFont(font)
        self.actResetAll.setObjectName("actResetAll")
        self.actUndo = QtWidgets.QAction(QWFormSetWeight2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.actUndo.setFont(font)
        self.actUndo.setObjectName("actUndo")
        self.actRedo = QtWidgets.QAction(QWFormSetWeight2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.actRedo.setFont(font)
        self.actRedo.setObjectName("actRedo")
        self.actResetLoc = QtWidgets.QAction(QWFormSetWeight2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.actResetLoc.setFont(font)
        self.actResetLoc.setObjectName("actResetLoc")
        self.actSeparator1 = QtWidgets.QAction(QWFormSetWeight2)
        self.actSeparator1.setEnabled(False)
        self.actSeparator1.setObjectName("actSeparator1")
        self.actSeparator2 = QtWidgets.QAction(QWFormSetWeight2)
        self.actSeparator2.setEnabled(False)
        self.actSeparator2.setObjectName("actSeparator2")
        self.actSeparator3 = QtWidgets.QAction(QWFormSetWeight2)
        self.actSeparator3.setEnabled(False)
        self.actSeparator3.setObjectName("actSeparator3")

        self.retranslateUi(QWFormSetWeight2)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QWFormSetWeight2)

    def retranslateUi(self, QWFormSetWeight2):
        _translate = QtCore.QCoreApplication.translate
        QWFormSetWeight2.setWindowTitle(_translate("QWFormSetWeight2", "Form"))
        self.tabWidget.setWhatsThis(_translate("QWFormSetWeight2", "<html><head/><body><p><br/></p></body></html>"))
        self.tree_overall.headerItem().setText(0, _translate("QWFormSetWeight2", "Test Conditions"))
        self.tree_overall.headerItem().setText(1, _translate("QWFormSetWeight2", "Weight_F (%)"))
        self.tree_overall.headerItem().setText(2, _translate("QWFormSetWeight2", "Weight_R (%)"))
        self.tree_overall.headerItem().setText(3, _translate("QWFormSetWeight2", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.overall), _translate("QWFormSetWeight2", "Overall"))
        self.tree_general.headerItem().setText(0, _translate("QWFormSetWeight2", "Parameters"))
        self.tree_general.headerItem().setText(1, _translate("QWFormSetWeight2", "Weight_F (%)"))
        self.tree_general.headerItem().setText(2, _translate("QWFormSetWeight2", "Weight_R (%)"))
        self.tree_general.headerItem().setText(3, _translate("QWFormSetWeight2", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.general), _translate("QWFormSetWeight2", "General"))
        self.tree_longi.headerItem().setText(0, _translate("QWFormSetWeight2", "Parameters"))
        self.tree_longi.headerItem().setText(1, _translate("QWFormSetWeight2", "Weight_F (%)"))
        self.tree_longi.headerItem().setText(2, _translate("QWFormSetWeight2", "Weight_R (%)"))
        self.tree_longi.headerItem().setText(3, _translate("QWFormSetWeight2", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.longi), _translate("QWFormSetWeight2", "Longitudinal"))
        self.tree_lateral.headerItem().setText(0, _translate("QWFormSetWeight2", "Parameters"))
        self.tree_lateral.headerItem().setText(1, _translate("QWFormSetWeight2", "Weight_F (%)"))
        self.tree_lateral.headerItem().setText(2, _translate("QWFormSetWeight2", "Weight_R (%)"))
        self.tree_lateral.headerItem().setText(3, _translate("QWFormSetWeight2", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.lateral), _translate("QWFormSetWeight2", "Lateral"))
        self.tree_vertical.headerItem().setText(0, _translate("QWFormSetWeight2", "Parameters"))
        self.tree_vertical.headerItem().setText(1, _translate("QWFormSetWeight2", "Weight_F (%)"))
        self.tree_vertical.headerItem().setText(2, _translate("QWFormSetWeight2", "Weight_R (%)"))
        self.tree_vertical.headerItem().setText(3, _translate("QWFormSetWeight2", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.vertical), _translate("QWFormSetWeight2", "Vertical"))
        self.tree_steer.headerItem().setText(0, _translate("QWFormSetWeight2", "Parameters"))
        self.tree_steer.headerItem().setText(1, _translate("QWFormSetWeight2", "Weight_F (%)"))
        self.tree_steer.headerItem().setText(2, _translate("QWFormSetWeight2", "Weight_R (%)"))
        self.tree_steer.headerItem().setText(3, _translate("QWFormSetWeight2", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.steer), _translate("QWFormSetWeight2", "Steer"))
        self.tree_roll.headerItem().setText(0, _translate("QWFormSetWeight2", "Parameters"))
        self.tree_roll.headerItem().setText(1, _translate("QWFormSetWeight2", "Weight_F (%)"))
        self.tree_roll.headerItem().setText(2, _translate("QWFormSetWeight2", "Weight_R (%)"))
        self.tree_roll.headerItem().setText(3, _translate("QWFormSetWeight2", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.roll), _translate("QWFormSetWeight2", "Roll"))
        self.label.setText(_translate("QWFormSetWeight2", "Front Suspension (%):"))
        self.label_2.setText(_translate("QWFormSetWeight2", "Rear Suspension (%):"))
        self.actImport.setText(_translate("QWFormSetWeight2", "Import Setting"))
        self.actSave.setText(_translate("QWFormSetWeight2", "Save Setting As"))
        self.actResetAll.setText(_translate("QWFormSetWeight2", "Reset All"))
        self.actUndo.setText(_translate("QWFormSetWeight2", "Undo"))
        self.actRedo.setText(_translate("QWFormSetWeight2", "Redo"))
        self.actResetLoc.setText(_translate("QWFormSetWeight2", "Reset Current Page"))
        self.actSeparator1.setText(_translate("QWFormSetWeight2", "|"))
        self.actSeparator2.setText(_translate("QWFormSetWeight2", "|"))
        self.actSeparator3.setText(_translate("QWFormSetWeight2", "|"))

