# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QWFormResult1.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QWFormResult1(object):
    def setupUi(self, QWFormResult1):
        QWFormResult1.setObjectName("QWFormResult1")
        QWFormResult1.setEnabled(True)
        QWFormResult1.resize(900, 500)
        self.tabWidget = QtWidgets.QTabWidget(QWFormResult1)
        self.tabWidget.setGeometry(QtCore.QRect(420, 70, 500, 238))
        self.tabWidget.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.overall = QtWidgets.QWidget()
        self.overall.setObjectName("overall")
        self.gridLayout = QtWidgets.QGridLayout(self.overall)
        self.gridLayout.setObjectName("gridLayout")
        self.tree_overall = QtWidgets.QTreeWidget(self.overall)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.tree_overall.setFont(font)
        self.tree_overall.setObjectName("tree_overall")
        self.gridLayout.addWidget(self.tree_overall, 0, 0, 1, 1)
        self.tabWidget.addTab(self.overall, "")
        self.test1 = QtWidgets.QWidget()
        self.test1.setObjectName("test1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.test1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tree_test1 = QtWidgets.QTreeWidget(self.test1)
        self.tree_test1.setObjectName("tree_test1")
        self.gridLayout_2.addWidget(self.tree_test1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.test1, "")
        self.test2 = QtWidgets.QWidget()
        self.test2.setObjectName("test2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.test2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tree_test2 = QtWidgets.QTreeWidget(self.test2)
        self.tree_test2.setObjectName("tree_test2")
        self.gridLayout_3.addWidget(self.tree_test2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.test2, "")
        self.test3 = QtWidgets.QWidget()
        self.test3.setObjectName("test3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.test3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tree_test3 = QtWidgets.QTreeWidget(self.test3)
        self.tree_test3.setObjectName("tree_test3")
        self.gridLayout_4.addWidget(self.tree_test3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.test3, "")
        self.test4 = QtWidgets.QWidget()
        self.test4.setObjectName("test4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.test4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tree_test4 = QtWidgets.QTreeWidget(self.test4)
        self.tree_test4.setObjectName("tree_test4")
        self.gridLayout_5.addWidget(self.tree_test4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.test4, "")
        self.test5 = QtWidgets.QWidget()
        self.test5.setObjectName("test5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.test5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tree_test5 = QtWidgets.QTreeWidget(self.test5)
        self.tree_test5.setObjectName("tree_test5")
        self.gridLayout_6.addWidget(self.tree_test5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.test5, "")
        self.test6 = QtWidgets.QWidget()
        self.test6.setObjectName("test6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.test6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tree_test6 = QtWidgets.QTreeWidget(self.test6)
        self.tree_test6.setObjectName("tree_test6")
        self.gridLayout_7.addWidget(self.tree_test6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.test6, "")
        self.test7 = QtWidgets.QWidget()
        self.test7.setObjectName("test7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.test7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tree_test7 = QtWidgets.QTreeWidget(self.test7)
        self.tree_test7.setObjectName("tree_test7")
        self.gridLayout_8.addWidget(self.tree_test7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.test7, "")
        self.test8 = QtWidgets.QWidget()
        self.test8.setObjectName("test8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.test8)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tree_test8 = QtWidgets.QTreeWidget(self.test8)
        self.tree_test8.setObjectName("tree_test8")
        self.gridLayout_9.addWidget(self.tree_test8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.test8, "")
        self.test10 = QtWidgets.QWidget()
        self.test10.setObjectName("test10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.test10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tree_test10 = QtWidgets.QTreeWidget(self.test10)
        self.tree_test10.setObjectName("tree_test10")
        self.gridLayout_10.addWidget(self.tree_test10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.test10, "")
        self.strapped = QtWidgets.QWidget()
        self.strapped.setObjectName("strapped")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.strapped)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.tree_strapped = QtWidgets.QTreeWidget(self.strapped)
        self.tree_strapped.setObjectName("tree_strapped")
        self.gridLayout_11.addWidget(self.tree_strapped, 0, 0, 1, 1)
        self.tabWidget.addTab(self.strapped, "")
        self.lineEdit = QtWidgets.QLineEdit(QWFormResult1)
        self.lineEdit.setGeometry(QtCore.QRect(600, 0, 108, 50))
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border: 2px groove gray;\n"
"    border-radius: 22px;\n"
"    padding: 2px 4px;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 100, 0);\n"
"}")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.actSelect = QtWidgets.QAction(QWFormResult1)
        self.actSelect.setCheckable(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actSelect.setIcon(icon)
        self.actSelect.setObjectName("actSelect")

        self.retranslateUi(QWFormResult1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QWFormResult1)

    def retranslateUi(self, QWFormResult1):
        _translate = QtCore.QCoreApplication.translate
        QWFormResult1.setWindowTitle(_translate("QWFormResult1", "Form"))
        self.tabWidget.setWhatsThis(_translate("QWFormResult1", "<html><head/><body><p><br/></p></body></html>"))
        self.tree_overall.headerItem().setText(0, _translate("QWFormResult1", "Tests"))
        self.tree_overall.headerItem().setText(1, _translate("QWFormResult1", "Similarity (%)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.overall), _translate("QWFormResult1", "Overall"))
        self.tree_test1.headerItem().setText(0, _translate("QWFormResult1", "Parameters"))
        self.tree_test1.headerItem().setText(1, _translate("QWFormResult1", "Similarity (%)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test1), _translate("QWFormResult1", "Long. braking"))
        self.tree_test2.headerItem().setText(0, _translate("QWFormResult1", "Parameters"))
        self.tree_test2.headerItem().setText(1, _translate("QWFormResult1", "Similarity (%)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test2), _translate("QWFormResult1", "Lat. 0_in"))
        self.tree_test3.headerItem().setText(0, _translate("QWFormResult1", "Parameters"))
        self.tree_test3.headerItem().setText(1, _translate("QWFormResult1", "Similarity (%)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test3), _translate("QWFormResult1", "Lat. 0_anti"))
        self.tree_test4.headerItem().setText(0, _translate("QWFormResult1", "Parameters"))
        self.tree_test4.headerItem().setText(1, _translate("QWFormResult1", "Similarity (%)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test4), _translate("QWFormResult1", "Lat. -30_in"))
        self.tree_test5.headerItem().setText(0, _translate("QWFormResult1", "Parameters"))
        self.tree_test5.headerItem().setText(1, _translate("QWFormResult1", "Similarity (%)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test5), _translate("QWFormResult1", "Alig. T_in"))
        self.tree_test6.headerItem().setText(0, _translate("QWFormResult1", "Parameters"))
        self.tree_test6.headerItem().setText(1, _translate("QWFormResult1", "Similarity (%)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test6), _translate("QWFormResult1", "Alig. T_anti"))
        self.tree_test7.headerItem().setText(0, _translate("QWFormResult1", "Parameters"))
        self.tree_test7.headerItem().setText(1, _translate("QWFormResult1", "Similarity (%)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test7), _translate("QWFormResult1", "Steering"))
        self.tree_test8.headerItem().setText(0, _translate("QWFormResult1", "Parameters"))
        self.tree_test8.headerItem().setText(1, _translate("QWFormResult1", "Similarity (%)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test8), _translate("QWFormResult1", "Roll"))
        self.tree_test10.headerItem().setText(0, _translate("QWFormResult1", "Parameters"))
        self.tree_test10.headerItem().setText(1, _translate("QWFormResult1", "Similarity (%)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test10), _translate("QWFormResult1", "Vertical"))
        self.tree_strapped.headerItem().setText(0, _translate("QWFormResult1", "Parameters"))
        self.tree_strapped.headerItem().setText(1, _translate("QWFormResult1", "Similarity (%)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.strapped), _translate("QWFormResult1", "Long. acc"))
        self.actSelect.setText(_translate("QWFormResult1", "Select"))
        self.actSelect.setToolTip(_translate("QWFormResult1", "Select to see details"))


import res_rc
