# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QWFormResult2.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QWFormResult2(object):
    def setupUi(self, QWFormResult2):
        QWFormResult2.setObjectName("QWFormResult2")
        QWFormResult2.resize(1600, 1000)
        self.tabWidget = QtWidgets.QTabWidget(QWFormResult2)
        self.tabWidget.setGeometry(QtCore.QRect(70, 110, 500, 238))
        self.tabWidget.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.overall = QtWidgets.QWidget()
        self.overall.setObjectName("overall")
        self.gridLayout = QtWidgets.QGridLayout(self.overall)
        self.gridLayout.setObjectName("gridLayout")
        self.tree_overall = QtWidgets.QTreeWidget(self.overall)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.tree_overall.setFont(font)
        self.tree_overall.setObjectName("tree_overall")
        self.gridLayout.addWidget(self.tree_overall, 0, 0, 1, 1)
        self.tabWidget.addTab(self.overall, "")
        self.general = QtWidgets.QWidget()
        self.general.setObjectName("general")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.general)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tree_general = QtWidgets.QTreeWidget(self.general)
        self.tree_general.setObjectName("tree_general")
        self.gridLayout_2.addWidget(self.tree_general, 0, 0, 1, 1)
        self.tabWidget.addTab(self.general, "")
        self.longi = QtWidgets.QWidget()
        self.longi.setObjectName("longi")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.longi)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tree_longi = QtWidgets.QTreeWidget(self.longi)
        self.tree_longi.setObjectName("tree_longi")
        self.gridLayout_3.addWidget(self.tree_longi, 0, 0, 1, 1)
        self.tabWidget.addTab(self.longi, "")
        self.lateral = QtWidgets.QWidget()
        self.lateral.setObjectName("lateral")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.lateral)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tree_lateral = QtWidgets.QTreeWidget(self.lateral)
        self.tree_lateral.setObjectName("tree_lateral")
        self.gridLayout_4.addWidget(self.tree_lateral, 0, 0, 1, 1)
        self.tabWidget.addTab(self.lateral, "")
        self.vertical = QtWidgets.QWidget()
        self.vertical.setObjectName("vertical")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.vertical)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tree_vertical = QtWidgets.QTreeWidget(self.vertical)
        self.tree_vertical.setObjectName("tree_vertical")
        self.gridLayout_5.addWidget(self.tree_vertical, 0, 0, 1, 1)
        self.tabWidget.addTab(self.vertical, "")
        self.steer = QtWidgets.QWidget()
        self.steer.setObjectName("steer")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.steer)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tree_steer = QtWidgets.QTreeWidget(self.steer)
        self.tree_steer.setObjectName("tree_steer")
        self.gridLayout_6.addWidget(self.tree_steer, 0, 0, 1, 1)
        self.tabWidget.addTab(self.steer, "")
        self.roll = QtWidgets.QWidget()
        self.roll.setObjectName("roll")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.roll)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tree_roll = QtWidgets.QTreeWidget(self.roll)
        self.tree_roll.setObjectName("tree_roll")
        self.gridLayout_7.addWidget(self.tree_roll, 0, 0, 1, 1)
        self.tabWidget.addTab(self.roll, "")
        self.lineEdit = QtWidgets.QLineEdit(QWFormResult2)
        self.lineEdit.setGeometry(QtCore.QRect(250, 39, 108, 40))
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border: 2px groove gray;\n"
"    border-radius: 20px;\n"
"    padding: 2px 4px;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 100, 0);\n"
"}")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(QWFormResult2)
        self.label_2.setGeometry(QtCore.QRect(298, 80, 176, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setObjectName("label_2")
        self.Rb_F = QtWidgets.QLineEdit(QWFormResult2)
        self.Rb_F.setGeometry(QtCore.QRect(254, 80, 70, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Rb_F.sizePolicy().hasHeightForWidth())
        self.Rb_F.setSizePolicy(sizePolicy)
        self.Rb_F.setMinimumSize(QtCore.QSize(70, 0))
        self.Rb_F.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Rb_F.setFont(font)
        self.Rb_F.setStyleSheet("QLineEdit{\n"
"    border: 2px groove gray;\n"
"    border-radius: 14px;\n"
"    padding: 2px 4px;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(255, 140 ,0);\n"
"}")
        self.Rb_F.setAlignment(QtCore.Qt.AlignCenter)
        self.Rb_F.setReadOnly(True)
        self.Rb_F.setObjectName("Rb_F")
        self.label = QtWidgets.QLabel(QWFormResult2)
        self.label.setGeometry(QtCore.QRect(63, 80, 185, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(True)
        self.label.setObjectName("label")
        self.Rb_R = QtWidgets.QLineEdit(QWFormResult2)
        self.Rb_R.setGeometry(QtCore.QRect(480, 80, 70, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Rb_R.sizePolicy().hasHeightForWidth())
        self.Rb_R.setSizePolicy(sizePolicy)
        self.Rb_R.setMinimumSize(QtCore.QSize(70, 0))
        self.Rb_R.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Rb_R.setFont(font)
        self.Rb_R.setStyleSheet("QLineEdit{\n"
"    border: 2px groove gray;\n"
"    border-radius: 14px;\n"
"    padding: 2px 4px;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(255, 140 ,0);\n"
"}")
        self.Rb_R.setAlignment(QtCore.Qt.AlignCenter)
        self.Rb_R.setReadOnly(True)
        self.Rb_R.setObjectName("Rb_R")
        self.actSelect = QtWidgets.QAction(QWFormResult2)
        self.actSelect.setCheckable(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actSelect.setIcon(icon)
        self.actSelect.setObjectName("actSelect")

        self.retranslateUi(QWFormResult2)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QWFormResult2)

    def retranslateUi(self, QWFormResult2):
        _translate = QtCore.QCoreApplication.translate
        QWFormResult2.setWindowTitle(_translate("QWFormResult2", "Form"))
        self.tabWidget.setWhatsThis(_translate("QWFormResult2", "<html><head/><body><p><br/></p></body></html>"))
        self.tree_overall.headerItem().setText(0, _translate("QWFormResult2", "Test Conditions"))
        self.tree_overall.headerItem().setText(1, _translate("QWFormResult2", "Reliability_F (%)"))
        self.tree_overall.headerItem().setText(2, _translate("QWFormResult2", "Reliability_R (%)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.overall), _translate("QWFormResult2", "Overall"))
        self.tree_general.headerItem().setText(0, _translate("QWFormResult2", "Parameters"))
        self.tree_general.headerItem().setText(1, _translate("QWFormResult2", "Reliability_F (%)"))
        self.tree_general.headerItem().setText(2, _translate("QWFormResult2", "Reliability_R (%)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.general), _translate("QWFormResult2", "General"))
        self.tree_longi.headerItem().setText(0, _translate("QWFormResult2", "Parameters"))
        self.tree_longi.headerItem().setText(1, _translate("QWFormResult2", "Reliability_F (%)"))
        self.tree_longi.headerItem().setText(2, _translate("QWFormResult2", "Reliability_R (%)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.longi), _translate("QWFormResult2", "Longitudinal"))
        self.tree_lateral.headerItem().setText(0, _translate("QWFormResult2", "Parameters"))
        self.tree_lateral.headerItem().setText(1, _translate("QWFormResult2", "Reliability_F (%)"))
        self.tree_lateral.headerItem().setText(2, _translate("QWFormResult2", "Reliability_R (%)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.lateral), _translate("QWFormResult2", "Lateral"))
        self.tree_vertical.headerItem().setText(0, _translate("QWFormResult2", "Parameters"))
        self.tree_vertical.headerItem().setText(1, _translate("QWFormResult2", "Reliability_F (%)"))
        self.tree_vertical.headerItem().setText(2, _translate("QWFormResult2", "Reliability_R (%)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.vertical), _translate("QWFormResult2", "Vertical"))
        self.tree_steer.headerItem().setText(0, _translate("QWFormResult2", "Parameters"))
        self.tree_steer.headerItem().setText(1, _translate("QWFormResult2", "Reliability_F (%)"))
        self.tree_steer.headerItem().setText(2, _translate("QWFormResult2", "Reliability_R (%)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.steer), _translate("QWFormResult2", "Steer"))
        self.tree_roll.headerItem().setText(0, _translate("QWFormResult2", "Parameters"))
        self.tree_roll.headerItem().setText(1, _translate("QWFormResult2", "Reliability_F (%)"))
        self.tree_roll.headerItem().setText(2, _translate("QWFormResult2", "Reliability_R (%)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.roll), _translate("QWFormResult2", "Roll"))
        self.label_2.setText(_translate("QWFormResult2", "Rear Suspension (%):"))
        self.label.setText(_translate("QWFormResult2", "Front Suspension (%):"))
        self.actSelect.setText(_translate("QWFormResult2", "Select"))
        self.actSelect.setToolTip(_translate("QWFormResult2", "Select to see details"))


import res_rc
